name = "rah-stats"
type = "javascript"
main = "index.js"
compatibility_date = "2022-05-15"
workers_dev = true

kv_namespaces = [
  { binding = "ViewCounter", id = "47d2fbdb19204aaab95e04beb84506c8" }
]
